### ISSUE TITLE
RegExp literal in array causes "jasy.js.parse.Parser.SyntaxError: Syntax error: Missing operand. Found type: div"

### ISSUE THREAD

**Issue by csakatoku** [zynga/jasy#7]
Jasy(both 0.4.6 and 0.5 beta2) seems to treat RegExp literals in an array as syntax error.

The following code, 

```
core.Class("p.helloworld.App", {
    construct: function(settings) {
        var arr = [/pattern/];
    }
});
```

will output this error.

```
% ./jasyscript.py build
Jasy 0.5-beta2
Initialized project core
Initialized project p.helloworld
Detecting dependencies...
Traceback (most recent call last):
   File "/Users/csakatoku/.virtualenvs/jasy/bin/jasy", line 110, in <module>
   # skip...
  File "/Users/csakatoku/.virtualenvs/jasy/lib/python3.2/site-packages/jasy/js/parse/Parser.py", line 1311, in MultiplyExpression
    node = UnaryExpression(tokenizer, staticContext)
  File "/Users/csakatoku/.virtualenvs/jasy/lib/python3.2/site-packages/jasy/js/parse/Parser.py", line 1338, in UnaryExpression
    node = MemberExpression(tokenizer, staticContext, True)
  File "/Users/csakatoku/.virtualenvs/jasy/lib/python3.2/site-packages/jasy/js/parse/Parser.py", line 1367, in MemberExpression
    node = PrimaryExpression(tokenizer, staticContext)
  File "/Users/csakatoku/.virtualenvs/jasy/lib/python3.2/site-packages/jasy/js/parse/Parser.py", line 1535, in PrimaryExpression
    raise SyntaxError("Missing operand. Found type: %s" % tokenType, tokenizer)
jasy.js.parse.Parser.SyntaxError: Syntax error: Missing operand. Found type: div
p.helloworld.App:3
Closing session...
```

FYI, my jascript.py is here.
- https://gist.github.com/1787832

**Comment by swernerx** [comment]
Should be fixed in repo thanks to Ivo: https://github.com/wpbasti/jasy/pull/8

**Comment by csakatoku** [comment]
master HEAD works fine. Thank you for your prompt reply.

**Comment by swernerx** [comment]
You're welcome!
